2018-01-22 20:12:42,885 INFO     Waiting for connection on RFCOMM channel 2
2018-01-22 20:13:03,354 ERROR    Traceback (most recent call last):
2018-01-22 20:13:03,355 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 20:13:03,356 ERROR    main()
2018-01-22 20:13:03,356 ERROR      File "raspBT.py", line 96, in main
2018-01-22 20:13:03,357 ERROR    client_sock, client_info = server_sock.accept()
2018-01-22 20:13:03,358 ERROR      File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 129, in accept
2018-01-22 20:13:03,358 ERROR    client, addr = self._sock.accept ()
2018-01-22 20:13:03,359 ERROR    KeyboardInterrupt
2018-01-22 20:21:15,350 INFO     Waiting for connection on RFCOMM channel 2
2018-01-22 20:22:29,963 ERROR    Traceback (most recent call last):
2018-01-22 20:22:29,964 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 20:22:29,965 ERROR    main()
2018-01-22 20:22:29,965 ERROR      File "raspBT.py", line 96, in main
2018-01-22 20:22:29,966 ERROR    client_sock, client_info = server_sock.accept()
2018-01-22 20:22:29,967 ERROR      File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 129, in accept
2018-01-22 20:22:29,967 ERROR    client, addr = self._sock.accept ()
2018-01-22 20:22:29,968 ERROR    KeyboardInterrupt
2018-01-22 20:24:23,233 INFO     Waiting for connection on RFCOMM channel 2
2018-01-22 20:25:51,128 ERROR    Traceback (most recent call last):
2018-01-22 20:25:51,129 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 20:25:51,130 ERROR    main()
2018-01-22 20:25:51,131 ERROR      File "raspBT.py", line 96, in main
2018-01-22 20:25:51,132 ERROR    client_sock, client_info = server_sock.accept()
2018-01-22 20:25:51,133 ERROR      File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 129, in accept
2018-01-22 20:25:51,134 ERROR    client, addr = self._sock.accept ()
2018-01-22 20:25:51,134 ERROR    KeyboardInterrupt
2018-01-22 20:32:53,950 ERROR    Traceback (most recent call last):
2018-01-22 20:32:53,951 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 20:32:53,952 ERROR    main()
2018-01-22 20:32:53,953 ERROR      File "raspBT.py", line 64, in main
2018-01-22 20:32:53,954 ERROR    time.sleep(10)
2018-01-22 20:32:53,954 ERROR    KeyboardInterrupt
2018-01-22 20:42:55,437 INFO     Waiting for connection on RFCOMM channel 2
2018-01-22 20:45:38,907 ERROR    Traceback (most recent call last):
2018-01-22 20:45:38,908 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 20:45:38,909 ERROR    main()
2018-01-22 20:45:38,909 ERROR      File "raspBT.py", line 96, in main
2018-01-22 20:45:38,910 ERROR    client_sock, client_info = server_sock.accept()
2018-01-22 20:45:38,910 ERROR      File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 129, in accept
2018-01-22 20:45:38,911 ERROR    client, addr = self._sock.accept ()
2018-01-22 20:45:38,912 ERROR    KeyboardInterrupt
2018-01-22 20:46:06,904 INFO     Waiting for connection on RFCOMM channel 2
2018-01-22 20:46:43,546 ERROR    Traceback (most recent call last):
2018-01-22 20:46:43,547 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 20:46:43,548 ERROR    main()
2018-01-22 20:46:43,548 ERROR      File "raspBT.py", line 96, in main
2018-01-22 20:46:43,549 ERROR    client_sock, client_info = server_sock.accept()
2018-01-22 20:46:43,550 ERROR      File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 129, in accept
2018-01-22 20:46:43,551 ERROR    client, addr = self._sock.accept ()
2018-01-22 20:46:43,552 ERROR    KeyboardInterrupt
2018-01-22 20:47:12,762 INFO     Waiting for connection on RFCOMM channel 2
2018-01-22 20:47:58,521 ERROR    Traceback (most recent call last):
2018-01-22 20:47:58,522 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 20:47:58,523 ERROR    main()
2018-01-22 20:47:58,523 ERROR      File "raspBT.py", line 96, in main
2018-01-22 20:47:58,524 ERROR    client_sock, client_info = server_sock.accept()
2018-01-22 20:47:58,524 ERROR      File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 129, in accept
2018-01-22 20:47:58,525 ERROR    client, addr = self._sock.accept ()
2018-01-22 20:47:58,526 ERROR    KeyboardInterrupt
2018-01-22 20:48:14,384 INFO     Waiting for connection on RFCOMM channel 2
2018-01-22 20:48:52,136 ERROR    Traceback (most recent call last):
2018-01-22 20:48:52,137 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 20:48:52,138 ERROR    main()
2018-01-22 20:48:52,138 ERROR      File "raspBT.py", line 96, in main
2018-01-22 20:48:52,139 ERROR    client_sock, client_info = server_sock.accept()
2018-01-22 20:48:52,140 ERROR      File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 129, in accept
2018-01-22 20:48:52,141 ERROR    client, addr = self._sock.accept ()
2018-01-22 20:48:52,142 ERROR    KeyboardInterrupt
2018-01-22 20:57:34,733 INFO     Waiting for connection on RFCOMM channel 2
2018-01-22 20:58:22,989 ERROR    Traceback (most recent call last):
2018-01-22 20:58:22,990 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 20:58:22,990 ERROR    main()
2018-01-22 20:58:22,991 ERROR      File "raspBT.py", line 96, in main
2018-01-22 20:58:22,992 ERROR    client_sock, client_info = server_sock.accept()
2018-01-22 20:58:22,992 ERROR      File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 129, in accept
2018-01-22 20:58:22,993 ERROR    client, addr = self._sock.accept ()
2018-01-22 20:58:22,994 ERROR    KeyboardInterrupt
2018-01-22 20:59:36,564 INFO     Waiting for connection on RFCOMM channel 2
2018-01-22 20:59:43,867 ERROR    Traceback (most recent call last):
2018-01-22 20:59:43,868 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 20:59:43,869 ERROR    main()
2018-01-22 20:59:43,869 ERROR      File "raspBT.py", line 96, in main
2018-01-22 20:59:43,870 ERROR    client_sock, client_info = server_sock.accept()
2018-01-22 20:59:43,871 ERROR      File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 129, in accept
2018-01-22 20:59:43,872 ERROR    client, addr = self._sock.accept ()
2018-01-22 20:59:43,873 ERROR    KeyboardInterrupt
2018-01-22 21:15:58,949 INFO     Waiting for connection on RFCOMM channel 2
2018-01-22 21:17:04,549 ERROR    Traceback (most recent call last):
2018-01-22 21:17:04,550 ERROR      File "raspBT.py", line 128, in <module>
2018-01-22 21:17:04,551 ERROR    main()
2018-01-22 21:17:04,552 ERROR      File "raspBT.py", line 96, in main
2018-01-22 21:17:04,553 ERROR    client_sock, client_info = server_sock.accept()
2018-01-22 21:17:04,554 ERROR      File "/usr/lib/python2.7/dist-packages/bluetooth/bluez.py", line 129, in accept
2018-01-22 21:17:04,554 ERROR    client, addr = self._sock.accept ()
2018-01-22 21:17:04,555 ERROR    KeyboardInterrupt
